### ISSUE TITLE
Does it work on MacOS?

### ISSUE THREAD

**Issue by OliverRovesik** [0ut0flin3/GPTalk#1]
Does it work on MacOS?

**Comment by 0ut0flin3** [comment]
it should. just use brew to install mpg321 instead of apt. as for portaudio it may be necessary to build it from source. can you try and tell me how it goes?

**Comment by OliverRovesik** [comment]
I don’t know if I can make it cuz I know nothing about python. But I’ll try with the help of Chatgpt. I’ll keep you updated.
