### ISSUE TITLE
doesnt' react

### ISSUE THREAD

**Issue by ifoundamachine** [0ut0flin3/GPTalk#5]
I have an env file inside the folder with the session API token copied straight from the website dashboard (it has about 50 characters). I run in my terminal: python3 app.py 2>/dev/null 

The app starts and says 
-------------------------
OPENAI's text-davinci-003
-------------------------
AI Memories loaded

-- and then... nothing happens. Something is missing in the way I set it up.

**Comment by 0ut0flin3** [comment]
> 

I've just updated a new version with fixed bugs, use the updated version.
erase 2>/dev/null and tell me what is printed

**Comment by ifoundamachine** [comment]
I installed the updated version, but when I type it python3 app.py, it prints:
-------------------------
OPENAI's text-davinci-003
-------------------------
AI Memories loaded


and that's it. Nothing else happens, it doesnt detect my voice etc. 
Do I need to run anything else? The server or something?

**Comment by 0ut0flin3** [comment]
first tell me what operating system are you doing this on? (Windows,Linux,etc)

**Comment by ifoundamachine** [comment]
MacOs Monterey Version 12.0

**Comment by 0ut0flin3** [comment]
> MacOs Monterey Version 12.0 Visual Studio Code

not tested yet on a Mac. Please be patient I will test that everything works fine on a Mac too. Please provide a screenshot of your terminal after you run the app. Thank you

**Comment by ifoundamachine** [comment]
<img width="1009" alt="Screenshot 2023-01-17 at 12 17 04" src="https://user-images.githubusercontent.com/13168583/212885679-5ee4b296-57f3-4f95-b486-f63dcc817429.png">
